"""authors and books

Revision ID: cb3797afa779
Revises: 8edef8d115c9
Create Date: 2025-01-26 10:22:30.168644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb3797afa779'
down_revision: Union[str, None] = '8edef8d115c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('biography', sa.String(), nullable=False),
    sa.Column('birthdate', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('library', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'library', 'authors', ['author_id'], ['id'])
    op.drop_column('library', 'author')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'library', type_='foreignkey')
    op.drop_column('library', 'author_id')
    op.drop_table('authors')
    # ### end Alembic commands ###
